apply plugin: 'com.android.library'
group = 'org.CreadoresProgram'
version = '1.1.0'

android {
    namespace 'org.CreadoresProgram.WebViewCREA'
    compileSdkVersion 25

    defaultConfig {
        targetSdkVersion 25
        versionCode 3
        versionName "1.1.0"
    }
    flavorDimensions "sdkVersion"
    productFlavors {
        standard {
            dimension "sdkVersion"
            minSdkVersion 9
        }
        legacy20 {
            dimension "sdkVersion"
            minSdkVersion 7
        }
    }
}

dependencies {
    standardCompileOnly 'com.squareup.okhttp3:okhttp:3.12.13'
}
